baseURL = "https://dineshbhagat.github.io/public"
languageCode = "en-us"

[params]
    title = "Dinesh Bhagat"
    author = "Dinesh Bhagat"
    description = ""
    copyright = ""
    copyright_link = ""

    # Profile section
    [params.profile]
        name = "Dinesh Bhagat"
        photo = "a.png"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
        class = "fab"
        icon = "fa-linkedin-in"
        url = "https://www.linkedin.com/in/dineshbhagat"
        title = "LinkedIn"

        [[params.social.list]]
        class = "fab"
        icon = "fa-github"
        url = "https://github.com/dineshbhagat"
        title = "GitHub"
	

    # Education section
    [params.education]
        title = "Education"

        [[params.education.list]]
        degree = "M.Tech"
        college = "VTU"
        dates = "2011 - 2013"
        thesis_title = "Title of the dissertation"
        thesis_link = "#"

        [[params.education.list]]
        degree = "B.E."
        college = "Mumbai University"
        dates = "2006 - 2010"

    # Languages section
    [params.language]
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Fluent"


    [params.aboutme]
        description = "Software engineer"

    # Experiences section
    [params.experiences]
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Sr. Software Engineer"
        dates = "2018 - *Present*"
		link = "https://www.target.com"
        company = "Target"

        [[params.jobs.list]]
        position = "SDE-2"
        dates = "2016 - 2018"
		link = "https://www.olacabs.com/"
        company = "Olacabs"
        details = "Brief description of the `work` done. Lorem ipsum."

    # Projects section
    [params.projects]
        icon = "fa-project-diagram"
        title = "Projects"

        [[params.projects.list]]
        title = "Awesome Project 1"
        url = "#"
        description = "Description of the *awesome* project 1"
		
		[[params.projects.list]]
        title = "Awesome Project 2"
        url = "#"
        description = "Description of the **awesome** project 2. Lorem ipsum dolor sit amet."

    # Skills section
    [params.skills]
        icon = "fa-cogs"
        title = "Skills"

        [[params.skills.list]]
        skill = "Java related technologies, SQL"
        skillrating = 90 # out of 100
                
        [[params.skills.list]]
        skill = "Python"
        skillrating = 20
		
        [[params.skills.list]]
        skill = "Golang"
        skillrating = 20
